#### DoD Monsternomicon Changes ####
# Ash-eating Neck
RRRM_AshNeck:
  AshLands:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1.33
        1: 1.43
        2: 1.53
        3: 1.63
        4: 1.73
        5: 1.83
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
#Burned Bones
RRRM_BurnedBones:
  AshLands:
    health:
        0: 1.33
        1: 1.38
        2: 1.43
        3: 1.48
        4: 1.53
        5: 1.58
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Dammed One
RRRM_DammedOne:
  AshLands:
    health:
        0: 1.33
        1: 1.38
        2: 1.43
        3: 1.48
        4: 1.53
        5: 1.58
    damage: 
        0: 1.33
        1: 1.43
        2: 1.54
        3: 1.63
        4: 1.73
        5: 1.83
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# ElderSurtling
RRRM_ElderSurtling:
  AshLands:
    health:
        0: 2
        1: 2.05
        2: 2.1
        3: 2.15
        4: 2.2
        5: 2.25
    damage: 
        0: 1.33
        1: 1.43
        2: 1.53
        3: 1.63
        4: 1.73
        5: 1.83
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# SmallAshNeck
RRRM_SmallAshNeck:
  Swamp:
    health:
        0: 2
        1: 2.05
        2: 2.1
        3: 2.15
        4: 2.2
        5: 2.25
    damage: 
        0: 2
        1: 2.1
        2: 2.2
        3: 2.3
        4: 2.4
        5: 2.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25